### ISSUE TITLE
Over wan not working tested with ngrok,playit

### ISSUE THREAD

**Issue by Echtar** [EntySec/SeaShell#10]
I tried on local lan and it worked but i tried over wan using ngrok and playit but the connection never come idk why
![IMG_7100](https://github.com/EntySec/SeaShell/assets/107372414/bc5ab01c-f291-48de-a95d-54f97f1a420f)

As you can see i put while generating ipa host name that ngrok gave to me and the port too
And i start listening on 127.0.0.1 and 1177 port

Note: ngrok and playit working
 with other rats like (AsyncRAT)

**Comment by enty8080** [comment]
@Echtar I am sorry, but this question is not related to SeaShell, please open issue only if you have something related to it.
