### ISSUE TITLE
Cam command not working

### ISSUE THREAD

**Issue by MildPepperCat** [EntySec/SeaShell#16]
**Describe the bug**
Description: running a command did not receive an expected outcome and resulted in an error

**To Reproduce**
1. Start TCP server.
2. Connect to server by running injected app on the phone
3. Run `devices -i 0`
4. Run `cam -s 0 <insert directory>`
5. Get error: `Failed to read device #0!`

**Expected behavior**
Expected to receive image in the directory specified and not receive an error.

**Screenshots**
![image](https://github.com/EntySec/SeaShell/assets/140764166/ef833ead-ec84-4088-824c-77289d6bc217)

**Desktop:**
 - OS: Linux Mint Cinnamon
 - Browser Mozilla Firefox
 - Version: 121.0.1+linuxmint1+virginia

**Smartphone:**
 - Device: iPhone 6s and iPhone 13 (My Personal Devices)
 - OS: iOS 15.2 (iPhone 6s) and iOS 16.6 beta 1 (iPhone 13)
 - Browser: Safari
 - Version: iOS 15.2 (iPhone 6s) and iOS 16.6 beta 1 (iPhone 13)

**Comment by enty8080** [comment]
Duplicate #9
