### ISSUE TITLE
does not work on the global network, but only on the local network

### ISSUE THREAD

**Issue by kenzWeb** [EntySec/SeaShell#17]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

If you connect to the ip using dynamic dns , the device that is logged into the application does not display, it turns out that so far it works only in the local network

**Comment by enty8080** [comment]
@kenzWeb It shouldn't, you should configure port forwarding if you want it to work over global network.

**Comment by kenzWeb** [comment]
> @kenzWeb It shouldn't, you should configure port forwarding if you want it to work over global network.

Got it, thanks. How can I do that?

**Comment by 0Clay01** [comment]
Did u figure it out ? How to
Global ?
