### ISSUE TITLE
I have problem when iam trying to start listener if it it's netcat or also in seashell it self so please can u help how could i connect

### ISSUE THREAD

**Issue by mahamedmahad1** [EntySec/SeaShell#22]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by enty8080** [comment]
What is your python version?

**Comment by mahamedmahad1** [comment]
Python 3.11.8

**Comment by mahamedmahad1** [comment]
Can u tell me what shall ido

**Comment by mahamedmahad1** [comment]
Which version should i use

**Comment by enty8080** [comment]
Try updating to the latest version, aka 3.12

**Comment by mahamedmahad1** [comment]
Still not working here is my screen

**Comment by enty8080** [comment]
I can't see your screen

**Comment by mahamedmahad1** [comment]
Still not working

**Comment by enty8080** [comment]
@mahamedmahad1 Refer to #19, send your python3 version, OS version and other details. I can't help you if I don't know what software you are using.

**Comment by mahamedmahad1** [comment]
Iam using python3.12.2 kali linux virtual machine
64-bit version of Windows
What else?

**Comment by enty8080** [comment]
@mahamedmahad1 I'll check this issue, give me some time

**Comment by mahamedmahad1** [comment]
Okey
