### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by purpo9** [EntySec/SeaShell#28]
Hello, 
I can't run SeaShell. Could you help me please ?

When I run the command it appears in the last two line:
import distutils.sysconfig
ModuleNotFoundError: No module named 'distutils'

Thank you

**Comment by enty8080** [comment]
Try `pip3 install setuptools`

**Comment by purpo9** [comment]
Hey thanks for your answer, 
But I've already tried, I've python-setuptools 69.2.0 on my MacBook M1
Regards,

**Comment by enty8080** [comment]
Try searching for solution here - https://stackoverflow.com/questions/69919970/no-module-named-distutils-but-distutils-installed

That's the only I found.

Or try:

```
python3 -m pip install distutils setuptools
```

**Comment by enty8080** [comment]
No response for 3 weeks. Closing as not relevant.
