### ISSUE TITLE
module 'PIL.Image' has no attribute 'ANTIALIAS'!

### ISSUE THREAD

**Issue by samallman87** [EntySec/SeaShell#3]
**Describe the bug**
when trying to generate the .ipa i get an error after entering the path to save the IPA:  An error occurred: module 'PIL.Image' has no attribute 'ANTIALIAS'!

**To Reproduce**
(seashell)> ipa
[>] Application name (Mussel): seaShell
[>] Bundle ID (com.entysec.mussel): com.seaShell.seaShell
[?] Add application icon [y/N]: n
[>] Host to connect back: 192.168.2.116
[>] Port to connect back: 8888
[>] Path to save the IPA: seaShell.ipa
[-] An error occurred: module 'PIL.Image' has no attribute 'ANTIALIAS'!

**Expected behavior**
an .ipa file is generated and saved to ~/

**Desktop (please complete the following information):**
 - OS: macOS 13.6.1, macbook pro 9,2
 - Version: SeaShell Framework 1.0.0

**Comment by enty8080** [comment]
@samallman87 Thank you for submitting this issue. Bug was fixed. Please update using:

```
pip3 install --force-reinstall git+https://github.com/EntySec/SeaShell
```
