### ISSUE TITLE
This error originates from a subprocess, and is likely not a problem with pip

### ISSUE THREAD

**Issue by Zets9** [EntySec/SeaShell#30]
This error originates from a subprocess, and is likely not a problem with pip.

How to fix that??
![Screenshot_394](https://github.com/EntySec/SeaShell/assets/163694085/84ba89db-0729-4094-8344-1867b63c740b)

**Comment by enty8080** [comment]
This is pip error. The solution is on the screen. Update Microsoft Visual C++
