### ISSUE TITLE
Missing some modules from py (ig)

### ISSUE THREAD

**Issue by MoonDevelopper** [EntySec/SeaShell#31]
[-] An error occurred: Instagram is not a zip file!
  File "/usr/local/bin/seashell", line 8, in <module>
    sys.exit(cli())
  File "/home/kali/.local/lib/python3.11/site-packages/seashell/__init__.py", line 105, in cli
    console.console()
  File "/home/kali/.local/lib/python3.11/site-packages/seashell/core/console.py", line 198, in console
    result = self.runtime.catch(self.shell)
  File "/home/kali/.local/lib/python3.11/site-packages/hatsploit/lib/runtime.py", line 126, in catch
    traceback.print_stack(file=sys.stdout)

I tried to reinstall seashell then something like this pop out on the red : 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.                                                                                                                                                              
faraday-agent-dispatcher 3.2.1 requires pytenable, which is not installed.                                                                                            
mitmproxy 10.2.2 requires mitmproxy-rs<0.6,>=0.5.1, which is not installed.                                                                                           
mitmproxy 10.2.2 requires urwid-mitmproxy<2.2,>=2.1.1, which is not installed.                                                                                        
crackmapexec 5.4.0 requires aioconsole<0.4.0,>=0.3.3, but you have aioconsole 0.7.0 which is incompatible.                                                            
crackmapexec 5.4.0 requires minikerberos==0.3.3, but you have minikerberos 0.4.0 which is incompatible.                                                               
crackmapexec 5.4.0 requires neo4j<5.0.0,>=4.1.1, but you have neo4j 5.2.dev0 which is incompatible.                                                                   
crackmapexec 5.4.0 requires paramiko<3.0.0,>=2.7.2, but you have paramiko 3.4.0 which is incompatible.                                                                
crackmapexec 5.4.0 requires pypsrp<0.8.0,>=0.7.0, but you have pypsrp 0.8.1 which is incompatible.                                                                    
crackmapexec 5.4.0 requires xmltodict<0.13.0,>=0.12.0, but you have xmltodict 0.13.0 which is incompatible.                                                           
faraday-agent-dispatcher 3.2.1 requires python-socketio==5.8.0, but you have python-socketio 5.7.2 which is incompatible.                                             
fastapi 0.101.0 requires starlette<0.28.0,>=0.27.0, but you have starlette 0.31.1 which is incompatible.                                                              
lsassy 3.1.6 requires impacket<0.10.0,>=0.9.22, but you have impacket 0.11.0 which is incompatible.                                                                   
lsassy 3.1.6 requires netaddr<0.9.0,>=0.8.0, but you have netaddr 1.2.1 which is incompatible.                                                                        
lsassy 3.1.6 requires rich<11.0.0,>=10.6.0, but you have rich 13.3.1 which is incompatible.                                                                           
mitmproxy 10.2.2 requires cryptography<41.1,>=39.0, but you have cryptography 42.0.5 which is incompatible.                                                           
mitmproxy 10.2.2 requires protobuf<5,>=3.14, but you have protobuf 5.26.1 which is incompatible.                                                                      
mitmproxy 10.2.2 requires pyOpenSSL<23.4,>=22.1, but you have pyopenssl 24.1.0 which is incompatible.                                                                 
notus-scanner 22.6.2 requires packaging<23.3, but you have packaging 24.0 which is incompatible.                                                                      
ospd-openvas 22.6.2 requires lxml<5.0.0,>=4.5.2, but you have lxml 5.2.1 which is incompatible.                                                                       
ospd-openvas 22.6.2 requires packaging<24.0,>=20.4, but you have packaging 24.0 which is incompatible.                                                                
ospd-openvas 22.6.2 requires redis>=4.5.0, but you have redis 4.3.4 which is incompatible.                                                                            
pyppeteer 1.0.1 requires pyee<9.0.0,>=8.1.0, but you have pyee 11.1.0 which is incompatible.                                                                          
pyppeteer 1.0.1 requires urllib3<2.0.0,>=1.25.8, but you have urllib3 2.2.1 which is incompatible.                                                                    
theharvester 4.5.1 requires aiohttp==3.9.3, but you have aiohttp 3.9.1 which is incompatible.                                                                         
theharvester 4.5.1 requires aiosqlite==0.19.0, but you have aiosqlite 0.17.0 which is incompatible.                                                                   
theharvester 4.5.1 requires dnspython==2.5.0, but you have dnspython 2.6.1 which is incompatible.                                                                     
theharvester 4.5.1 requires fastapi==0.109.0, but you have fastapi 0.101.0 which is incompatible.                                                                     
theharvester 4.5.1 requires lxml==5.1.0, but you have lxml 5.2.1 which is incompatible.                                                                               
theharvester 4.5.1 requires netaddr==0.10.1, but you have netaddr 1.2.1 which is incompatible.                                                                        
theharvester 4.5.1 requires pyppeteer==1.0.2, but you have pyppeteer 1.0.1 which is incompatible.                                                                     
theharvester 4.5.1 requires retrying==1.3.4, but you have retrying 1.3.3 which is incompatible.                                                                       
theharvester 4.5.1 requires setuptools==69.0.3, but you have setuptools 68.1.2 which is incompatible.                                                                 
theharvester 4.5.1 requires shodan==1.31.0, but you have shodan 1.30.1 which is incompatible.                                                                         
theharvester 4.5.1 requires slowapi==0.1.8, but you have slowapi 0.1.4 which is incompatible.                                                                         
theharvester 4.5.1 requires uvicorn==0.27.0.post1, but you have uvicorn 0.27.0 which is incompatible.

**Comment by MannuVilasara** [comment]
have u tried installing it in virtual environment

**Comment by enty8080** [comment]
Looks like not the issue with SeaShell.
