### ISSUE TITLE
Download/Upload Functions

### ISSUE THREAD

**Issue by havok87** [EntySec/SeaShell#36]
**Describe the bug**
Unable to download a remote file from attacker system onto device.
Unable to upload a local file to remote attacker system.

**To Reproduce Download Issue**
1. Establish C2 connection
2. Browse to /private/var/tmp on the iOS device
3. issue command 'download /path/to/remote/file /private/var/tmp'
4. See error 'downloadIssue1.png' and 'downloadIssue2.png'
<img width="372" alt="downloadIssue1" src="https://github.com/EntySec/SeaShell/assets/1557990/cfabd8f0-3ec4-438a-8a0f-03a3912ea507">
<img width="730" alt="downloadIssue2" src="https://github.com/EntySec/SeaShell/assets/1557990/bc69a0a5-0321-4cf6-a6fd-c58cd7c1c9d0">

**To Reproduce Upload Issue**
1. Establish C2 connection
2. Browse to /private/var/tmp on the iOS device
3. issue command 'upload /private/var/tmp/journeys/ /Users/dre/Tools/SeaShell/'
4. See error 'uploadIssue1.png' and 'uploadIssue2.png'
<img width="738" alt="uploadIssue1" src="https://github.com/EntySec/SeaShell/assets/1557990/f49658e2-d501-4adf-beb2-fc032d6b09d9">
<img width="333" alt="uploadIssue2" src="https://github.com/EntySec/SeaShell/assets/1557990/5589350b-7f9c-472d-8d4f-472ee3054501">

**Expected behavior**
The specified file on the remote attacker system should be downloaded into directory specified.
The specified file on the local system should be uploaded into directory specified on the  remote attacker system.

**Screenshots**
downloadIssue1.png
downloadIssue2.png
uploadIssue1.png
uploadIssue2.png

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1
 - M1 Max

**Smartphone (please complete the following information):**
 - Device: iPhone 13 pro
 - OS: iOS 16.6.1

**Comment by enty8080** [comment]
@havok87 You are passing wrong arguments to `download` and `upload` commands, it should be:

```
download <remote_file> <local_path>
upload <local_file> <remote_path>
```

So, in your situation:

```
download /private/var/tmp/test /Users/dre/Tools/SeaShell/screencapture
```
