### ISSUE TITLE
Unable to run SeaShell Framework. Can't load commands rpc and listener due to exceptions 

### ISSUE THREAD

**Issue by barkatthemoon18** [EntySec/SeaShell#39]
**Describe the bug**
I'm using WSL (Ubuntu) and MacOS Sonoma with different versions of Python (from 3.10 to 3.12) and the SeaShell refuses to load the rpc and listener commands. 

Errors are different from what was reported in #22 and #19.

I've been trying to install and also reinstall the framework (as shown in the update section) with no results. Also, I manually updated the pex package from pip, and other solutions provided in those two issues.

**To Reproduce**
Just run the pip3 command mentioned in the install section of the Readme.

**Screenshots**
![imagen](https://github.com/EntySec/SeaShell/assets/71537782/6f33b70f-b984-4150-be9f-08ad16c322f6)

**Desktop (please complete the following information):**
 - OS: Windows 11 + WSL Ubuntu (5.15.153.1-microsoft-standard-WSL2) / MacOS Sonoma (14.5)

**Comment by enty8080** [comment]
Thank you very much for the details. I've already fixed this problem. Can you please enter these commands and confirm if problem is solved:

```
pip3 uninstall pex
pip3 install git+https://github.com/EntySec/Pex
```

**Comment by barkatthemoon18** [comment]
No further loading issues have been found. Thanks for the fix and the reply as well! I will close it.
