### ISSUE TITLE
Linux / AUR

### ISSUE THREAD

**Issue by LilKurisuu** [EntySec/SeaShell#4]
Is it possible to add this to the AUR so it's possible to use on arch linux based distributions?

**Comment by enty8080** [comment]
@LilKurisuu It is python package so it needs to be installed by `pip3`. You can easily install it by the command in the `Installation` section of README.md

**Comment by authorisation** [comment]
Arch does not support pip.

**Comment by enty8080** [comment]
@authorisation Arch is a Linux, Linux supports pip. If Arch supports python then it should support pip.

**Comment by authorisation** [comment]
Arch has it's own package manager (pacman) and is incompatible with pip. The AUR is a great place for something like this.

```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.
```
P.S. No, thanks.

**Comment by enty8080** [comment]
@authorisation I don't know how to add it to AUR, I have no clue what is AUR and honestly I don't want to deal with Arch Linux in general. So, I'll wait for someone to add it there or for Arch Linux to add pip support.

**Comment by authorisation** [comment]
That's fine but I would keep the issue open in that case.
