### ISSUE TITLE
How to connect WLAN

### ISSUE THREAD

**Issue by StarsScreamF22** [EntySec/SeaShell#40]
**What is your question?**
When i build an ipa i use the default IP witch is 192.168.x.x, is that only for local connection?
How can i connect using Internet for remote control ? Do you know/recommend any method? 
Thank you 😄

**Additional context**

**Any suggestions for the docs?**
Describe how would you fix the documentation to solve the problem.

**Comment by StarsScreamF22** [comment]
i've already tried tunneling with playit.gg and telebit but nothing works, i have installed mussel using Trollstore installed by TrollsinstallerX, my trollstore is working, when i built the ipa i set de listener on the ip that the site (playit.gg and telebit) gave me, i dont know what to do

**Comment by ItzMatty3241** [comment]
you are probably using the same port on the payload  and the listener which I think might conflic with each other I got mine working using windows wsl and playit 
reach my discord if u still cant do it I'll gladly help :>
