### ISSUE TITLE
Unable to connect successfully

### ISSUE THREAD

**Issue by en0th** [EntySec/SeaShell#49]
**Describe the bug**
Unable to connect successfully.

**To Reproduce**
1. I created a machine using WLS on the Windows platform with an IP address of 192.168.43.219.
2. I followed the steps and created an IPA using the command `ipa-b`. My iPad (IOS16.6.1) IP is 192.168.43.164. 
3. I created a listener using the command `listener-L 0.0.0.0- p 8888`, and I turned off the Windows firewall.
4. Using the command `netstat - pantu | grep 8888` on WSLs, it was found that a connection had been established, but using the `devices - l` command to search for the connection did not find any devices.

**Expected behavior**
Expected to connect successfully and enter the interactive shell.

**Screenshots**
![image](https://github.com/user-attachments/assets/26be0f1e-4b0d-4258-938c-fd24375c552a)
![image](https://github.com/user-attachments/assets/c0e6c52e-a7e2-471d-a3c4-fbb86524bc4a)

**Desktop (please complete the following information):**
 - OS: Windows11
 - WSL OS: Kali

**Smartphone (please complete the following information):**
 - Device: IPad 2021
 - OS: IPadOS 16.6.1

**Comment by en0th** [comment]
I first executed 'rpc-L 0.0.0.0- p 8888' and then executed 'listener-L 0.0.0.0- p 8888'
`Then I received a reply saying 'New device connected'. I don't know how this was done.

**Comment by mishariveli** [comment]
i have the same issue idk if i should build the ipa with the ios ip or the pc ip and after should i run listener on port 8888 or rpc as the mussel app is not connecting back as shown and also the listener and rpc command only accepts port ( -p ) 

![Image](https://github.com/user-attachments/assets/55bc422b-3b8d-4c21-b6b1-fc3bf806640d)

![Image](https://github.com/user-attachments/assets/b3b2be92-0942-4eb9-8fff-2565dc0a4b8f)

![Image](https://github.com/user-attachments/assets/a0aa6c18-19f5-4827-9da5-3b64c7c3634d)
