### ISSUE TITLE
Regarding cocoatop and mussel

### ISSUE THREAD

**Issue by doraorak** [EntySec/SeaShell#5]
You said (on reddit) that this would cause a process named mussel to be visible in cocoatop. I want to know the limits of this. Does it show up once you install the ipa and stay there untill you reboot ? Does it only show up when you open the app and keep it running ? Does it only show up when the attacker is messing with the system ? Can i kill this process from cocoatop to prevent it ? Is there a way to see which app is infected after seeing mussel in cocoatop without prior knownledge ? Sorry if most of these were in docs. Thanks.

**Comment by enty8080** [comment]
@doraorak Thank you for reaching out!

Process appears right after user opens the application and stays active until attacker closes the session or a device reboots (it stays active even if application closed and deleted). Reboot fixes everything and kills the process as well.

Moreover, you can find the process by yourself and kill it. This will terminate the connection and attackers will lose control.

Best wishes,
Ivan Nikolskiy (@enty8080)
