### ISSUE TITLE
can't install seashell on macOS

### ISSUE THREAD

**Issue by def1ned** [EntySec/SeaShell#50]
admin@MacBook-Air-admin ~ % python3 -m seashell
/Applications/Xcode.app/Contents/Developer/usr/bin/python3: No module named seashell.__main__; 'seashell' is a package and cannot be directly executed

**Desktop (please complete the following information): MacBook Air M3**
 - OS: [macOS Sonoma 14.7]

**Comment by enty8080** [comment]
@def1ned SeaShell Framework should be installed using **pip3** and invoked via `seashell` command afterwards.

**Comment by def1ned** [comment]
wdym? I tried to install it with pip3 (pip3 install seashell) but it didn't worked (same issue)

**Comment by enty8080** [comment]
@def1ned If you installed it with pip3 it should work if you type **seashell** command in terminal. You shouldn't invoke it using **python3**

**Comment by def1ned** [comment]
> @def1ned If you installed it with pip3 it should work if you type **seashell** command in terminal. You shouldn't invoke it using **python3**

so, I will try it on linux..
