### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by nightwolf2100** [EntySec/SeaShell#7]
I have python3 installed and added to my path but seashell will not open after I run the install command. Is this user error or is their not windows support?

**Comment by enty8080** [comment]
@nightwolf2100 I am not using Windows hence have no opportunity to test if it works or now. Try using WSL instead if it does not work. I am not planning to support windows.

**Comment by Echtar** [comment]
> I have python3 installed and added to my path but seashell will not open after I run the install command. Is this user error or is their not windows support?

Its working on windows iam using it on windows
